api:
    resource: "@AppBundle/Controller/ApiController.php"
    prefix:   /api
    type:     annotation
    schemes:  [https]

hangman:
    resource: "@AppBundle/Controller/HangmanController.php"
    type:     annotation
    schemes:  [https]
